ALTER TYPE "CircleCardEventType" ADD VALUE IF NOT EXISTS 'SPIN_STARTED';
ALTER TYPE "CircleCardEventType" ADD VALUE IF NOT EXISTS 'SPIN_COMPLETED';
ALTER TYPE "CircleCardEventType" ADD VALUE IF NOT EXISTS 'SPIN_ALREADY_CONNECTED';
ALTER TYPE "CircleCardEventType" ADD VALUE IF NOT EXISTS 'SPIN_REQUIRES_ACCOUNT';
ALTER TYPE "CircleCardEventType" ADD VALUE IF NOT EXISTS 'SPIN_RETURNED_AFTER_SIGNUP';
ALTER TYPE "CircleCardEventType" ADD VALUE IF NOT EXISTS 'SPIN_CONNECTION_CREATED';
ALTER TYPE "CircleCardEventType" ADD VALUE IF NOT EXISTS 'FIRST_CONNECTION_CREATED';
