import { randomBytes } from "node:crypto";
import { createRequire } from "node:module";
import { execFileSync } from "node:child_process";
import { existsSync, realpathSync } from "node:fs";
import { join } from "node:path";
import { readEnvironmentJson } from "./environment-file.mjs";
import { APPLICATION_IDENTITIES, verifyApplicationCommit } from "./application-identities.mjs";
const require = createRequire(import.meta.url);
const { BUILD_ENV_KEYS } = require("./environment-groups.cjs");
const command = process.argv[2];
const role = process.argv[3];
if (!new Set(["prisma", "next", "verify"]).has(command)) throw new Error("Unknown build command.");
if (role !== "forward") throw new Error("Only the approved forward application uses this build entry point; rollback must use the Phase E3 provenance-gated fixture flow.");
if (process.getuid?.() === 0 || execFileSync("/usr/bin/id", ["-un"], { encoding: "utf8" }).trim() !== "phase-f1-build") throw new Error("Unprivileged build identity required.");
const cwd = realpathSync(process.cwd());
const expectedSha = APPLICATION_IDENTITIES[role].sha;
if (!cwd.startsWith(`/var/www/builds/${role}-${expectedSha}-`)) throw new Error("Build CWD is not a fresh role-bound checkout.");
verifyApplicationCommit(cwd, role);
const publicValues = readEnvironmentJson("/etc/thebusinesscircle/build/build.env.json", { allowedKeys: BUILD_ENV_KEYS, expectedGroup: "phase-f1-build" });
const environment = { HOME: "/var/lib/thebusinesscircle/build", USER: "phase-f1-build", LOGNAME: "phase-f1-build", PATH: "/usr/local/bin:/usr/bin:/bin", LANG: "C.UTF-8", TZ: "Europe/London", NODE_ENV: "production", NEXT_TELEMETRY_DISABLED: "1", APP_BRAND: "bcn", APP_URL: "https://thebusinesscircle.net", AUTH_URL: "https://thebusinesscircle.net", NEXTAUTH_URL: "https://thebusinesscircle.net", DATABASE_URL: "postgresql://phase_f1_build@127.0.0.1:1/phase_f1_build", AUTH_SECRET: randomBytes(48).toString("base64url"), NEXTAUTH_SECRET: randomBytes(48).toString("base64url"), CIRCLE_CARD_BILLING_ENABLED: "false", CIRCLE_CARD_BILLING_ACCESS_MODE: "operator", PHASE_F1_BUILD_ROLE: role, PHASE_F1_BUILD_APPLICATION_SHA: expectedSha, ...publicValues };
const targets = { prisma: [join(cwd, "node_modules/prisma/build/index.js"), "generate"], next: [join(cwd, "node_modules/next/dist/bin/next"), "build"], verify: [join(cwd, "scripts/verify-circle-card-action-build.mjs")] };
const [script, ...args] = targets[command];
if (!existsSync(script) || typeof process.execve !== "function") throw new Error("Required build executable or Node process.execve is absent.");
process.execve("/usr/bin/node", ["/usr/bin/node", script, ...args], environment);
