const FORWARD_APPLICATION_SHA = "2c83694de301b0244c5586c1598aceb10fa2214b";
const ROLLBACK_APPLICATION_SHA = "5d1f81bb05a01b08e1134785c2f86b77c8969fe3";
const HISTORICAL_PRODUCTION_SHA = "5fa2bbf6ac7d39aa14636882bbae2d2713faf11a";

const SHARED_KEYS = [
  "DATABASE_URL",
  "AUTH_SECRET",
  "NEXTAUTH_SECRET",
  "AUTH_BCRYPT_ROUNDS",
  "AUTH_MAGIC_LINK_ENABLED",
  "EMAIL_VERIFICATION_TOKEN_TTL_HOURS",
  "PASSWORD_RESET_TOKEN_TTL_MINUTES",
  "PENDING_REGISTRATION_TTL_HOURS",
  "STRIPE_SECRET_KEY",
  "STRIPE_CIRCLE_CARD_PRO_PRODUCT_ID",
  "STRIPE_CIRCLE_CARD_PRO_MONTHLY_PRICE_ID",
  "STRIPE_CIRCLE_CARD_PRO_ANNUAL_PRICE_ID",
  "STRIPE_CIRCLE_CARD_TEAMS_MONTHLY_PRICE_ID",
  "STRIPE_CIRCLE_CARD_TEAMS_ANNUAL_PRICE_ID",
  "CIRCLE_CARD_BILLING_PORTAL_CONFIGURATION_ID",
  "CIRCLE_CARD_BILLING_ENABLED",
  "CIRCLE_CARD_BILLING_ACCESS_MODE",
  "CIRCLE_CARD_BILLING_OPERATOR_USER_IDS",
  "CIRCLE_CARD_PLATFORM_OWNER_EMAILS",
  "UPSTASH_REDIS_REST_URL",
  "UPSTASH_REDIS_REST_TOKEN",
  "KV_REST_API_URL",
  "KV_REST_API_TOKEN",
  "RATE_LIMIT_REDIS_PREFIX",
  "CLOUDINARY_CLOUD_NAME",
  "CLOUDINARY_API_KEY",
  "CLOUDINARY_API_SECRET",
  "CLOUDINARY_CIRCLE_CARD_FOLDER",
  "CLOUDINARY_PROFILE_FOLDER",
  "CLOUDINARY_VISUAL_MEDIA_FOLDER",
  "CIRCLE_CARD_REMOTE_IMAGE_HOSTS",
  "OPENAI_API_KEY",
  "BUSINESS_CARD_SCAN_MODEL",
  "BUSINESS_CARD_OCR_TIMEOUT_MS",
  "NEXT_PUBLIC_APP_VERSION",
  "NEXT_PUBLIC_POSTHOG_KEY",
  "NEXT_PUBLIC_POSTHOG_HOST",
  "NEXT_PUBLIC_POSTHOG_DEBUG",
  "NEXT_PUBLIC_POSTHOG_REPLAY_SAMPLE_RATE",
  "NEXT_PUBLIC_ANALYTICS_DEBUG",
  "ANALYTICS_DEBUG"
];

const CIRCLE_CARD_ONLY_KEYS = [
  "CIRCLE_CARD_RESEND_API_KEY",
  "CIRCLE_CARD_RESEND_FROM_EMAIL",
  "CIRCLE_CARD_RESEND_REPLY_TO_EMAIL",
  "CIRCLE_CARD_PUBLIC_CONTACT_EMAIL"
];

// The BCN-owned Stripe webhook sends Circle lifecycle messages. These four
// Circle values are therefore deliberately present in both exact environments;
// no other Circle-only identity is copied into BCN.
const CIRCLE_LIFECYCLE_KEYS = [...CIRCLE_CARD_ONLY_KEYS];

// These names are compiled into browser output or build metadata. They remain
// classified as shared because server-side analytics reads the same values, but
// only this public subset may be copied into the authority-free build context.
const BUILD_ENV_KEYS = [
  "NEXT_PUBLIC_APP_VERSION",
  "NEXT_PUBLIC_ABLY_CHANNEL_PREFIX",
  "NEXT_PUBLIC_COMMUNITY_REALTIME_ENABLED",
  "NEXT_PUBLIC_FACEBOOK_URL",
  "NEXT_PUBLIC_GOOGLE_REVIEW_URL",
  "NEXT_PUBLIC_INSTAGRAM_URL",
  "NEXT_PUBLIC_LINKEDIN_URL",
  "NEXT_PUBLIC_POSTHOG_KEY",
  "NEXT_PUBLIC_POSTHOG_HOST",
  "NEXT_PUBLIC_POSTHOG_DEBUG",
  "NEXT_PUBLIC_POSTHOG_REPLAY_SAMPLE_RATE",
  "NEXT_PUBLIC_ANALYTICS_DEBUG",
  "NEXT_PUBLIC_TIKTOK_URL",
  "NEXT_PUBLIC_X_URL",
  "NEXT_PUBLIC_YOUTUBE_URL"
];

const DELIBERATELY_UNSUPPORTED_KEYS = [
  // A single compiled NEXT_PUBLIC origin cannot represent two runtime brands.
  // Runtime code must use the validated APP_URL/runtime-brand registry instead.
  "NEXT_PUBLIC_APP_URL",
  // Vercel deployment metadata is not applicable to this systemd/VPS release.
  "VERCEL_ENV",
  // Development, audit and one-off tooling authority is never copied to a
  // production runtime or build environment by this pack.
  "ALLOW_BCN_TEST_MEMBER_SCRIPT",
  "AUDIT_PUBLIC_OUTPUT_BASE_URL",
  "AUDIT_PUBLIC_OUTPUT_MODE",
  "BCN_RULES_TEST_PASSWORD",
  "BCN_RULES_TEST_TIER",
  "DEMO_MEMBER_PASSWORD",
  "RESEND_TEST_TO",
  "SMOKE_AUTH_SECRET",
  "SMOKE_DATABASE_URL",
  "SPIN_TEST_BASE_URL",
  "SPIN_TEST_SCREENSHOT"
];

const BCN_ONLY_KEYS = [
  "ADMIN_EMAIL",
  "PLATFORM_OWNER_EMAILS",
  "STRIPE_WEBHOOK_SECRET",
  "STRIPE_FOUNDATION_MONTHLY_PRICE_ID",
  "STRIPE_FOUNDATION_PRICE_ID",
  "STRIPE_STANDARD_PRICE_ID",
  "STRIPE_FOUNDATION_ANNUAL_PRICE_ID",
  "STRIPE_FOUNDING_FOUNDATION_MONTHLY_PRICE_ID",
  "STRIPE_FOUNDING_FOUNDATION_PRICE_ID",
  "STRIPE_FOUNDING_STANDARD_PRICE_ID",
  "STRIPE_FOUNDING_FOUNDATION_ANNUAL_PRICE_ID",
  "STRIPE_INNER_CIRCLE_MONTHLY_PRICE_ID",
  "STRIPE_INNER_CIRCLE_PRICE_ID",
  "STRIPE_INNER_CIRCLE_ANNUAL_PRICE_ID",
  "STRIPE_FOUNDING_INNER_CIRCLE_MONTHLY_PRICE_ID",
  "STRIPE_FOUNDING_INNER_CIRCLE_PRICE_ID",
  "STRIPE_FOUNDING_INNER_CIRCLE_ANNUAL_PRICE_ID",
  "STRIPE_CORE_MONTHLY_PRICE_ID",
  "STRIPE_CORE_PRICE_ID",
  "STRIPE_CORE_ANNUAL_PRICE_ID",
  "STRIPE_FOUNDING_CORE_MONTHLY_PRICE_ID",
  "STRIPE_FOUNDING_CORE_PRICE_ID",
  "STRIPE_FOUNDING_CORE_ANNUAL_PRICE_ID",
  "STRIPE_FOUNDER_CLARITY_AUDIT_PRICE_ID",
  "STRIPE_FOUNDER_GROWTH_ARCHITECT_MONTHLY_PRICE_ID",
  "STRIPE_FOUNDER_GROWTH_ARCHITECT_PRICE_ID",
  "STRIPE_FOUNDER_STRATEGY_SESSION_PRICE_ID",
  "STRIPE_FOUNDING_ACCESS_COUPON_ID",
  "STRIPE_FOUNDING_ACCESS_PROMOTION_CODE_ID",
  "RESEND_API_KEY",
  "RESEND_FROM_EMAIL",
  "RESEND_REPLY_TO_EMAIL",
  "PUBLIC_CONTACT_EMAIL",
  "CONTACT_NOTIFY_EMAIL",
  "RESEND_WEBHOOK_SECRET",
  "INBOUND_EMAIL_FORWARD_TO",
  "CRON_SECRET",
  "COMMUNITY_AUTOMATION_SECRET",
  "INTELLIGENCE_CRON_SECRET",
  "CIRCLE_CARD_ACTIVATION_SECRET",
  "RESOURCE_AUTOMATION_SECRET",
  "BCN_COMMUNITY_AUTOMATION_ENABLED",
  "BCN_COMMUNITY_AUTOMATION_THROTTLE_MS",
  "BCN_COMMUNITY_LOOKBACK_HOURS",
  "BCN_COMMUNITY_MAX_POSTS_PER_RUN",
  "BCN_COMMUNITY_SOURCE_NAME",
  "BCN_COMMUNITY_SOURCE_URL",
  "BCN_COMMUNITY_SOURCE_URLS",
  "BCN_INTELLIGENCE_EXTRA_SOURCE_URLS",
  "BCN_INTELLIGENCE_SOURCE_REGISTRY_ENABLED",
  "BCN_INTELLIGENCE_SOURCE_TIMEOUT_MS",
  "COMMUNITY_AUTOMATION_AUTHOR_ID",
  "COMMUNITY_PROMPT_AUTHOR_ID",
  "RESOURCE_AUTOMATION_THROTTLE_MS",
  "RESOURCE_CONTENT_MODEL",
  "RESOURCE_CORE_PUBLISH_TIMES",
  "RESOURCE_DAILY_CORE_PUBLISH_TIME",
  "RESOURCE_DAILY_FOUNDATION_PUBLISH_TIME",
  "RESOURCE_DAILY_INNER_PUBLISH_TIME",
  "RESOURCE_FOUNDATION_PUBLISH_TIMES",
  "RESOURCE_GENERATION_PROVIDER",
  "RESOURCE_IMAGE_FALLBACK_MODEL",
  "RESOURCE_IMAGE_MODEL",
  "RESOURCE_IMAGE_QUALITY",
  "RESOURCE_IMAGE_SIZE",
  "RESOURCE_INNER_PUBLISH_TIMES",
  "RESOURCE_SCHEDULE_TIMEZONE",
  "CLOUDINARY_RESOURCE_FOLDER",
  "OPENAI_RESOURCE_CONTENT_MODEL",
  "OPENAI_RESOURCE_IMAGE_FALLBACK_MODEL",
  "OPENAI_RESOURCE_IMAGE_MODEL",
  "ABLY_API_KEY",
  "ABLY_CHANNEL_PREFIX",
  "NEXT_PUBLIC_ABLY_CHANNEL_PREFIX",
  "NEXT_PUBLIC_COMMUNITY_REALTIME_ENABLED",
  "LIVEKIT_URL",
  "LIVEKIT_SERVER_URL",
  "LIVEKIT_API_KEY",
  "LIVEKIT_API_SECRET",
  "TURN_DOMAIN",
  "TURN_REALM",
  "TURN_SHARED_SECRET",
  "TURN_TLS_ENABLED",
  "TURN_TLS_PORT",
  "TURN_TLS_CERTS_DIR",
  "TURN_TLS_CERT_FILE",
  "TURN_TLS_KEY_FILE",
  "TURN_TTL_SECONDS",
  "TURN_UDP_PORT",
  "NEXT_PUBLIC_FACEBOOK_URL",
  "NEXT_PUBLIC_GOOGLE_REVIEW_URL",
  "NEXT_PUBLIC_INSTAGRAM_URL",
  "NEXT_PUBLIC_LINKEDIN_URL",
  "NEXT_PUBLIC_TIKTOK_URL",
  "NEXT_PUBLIC_X_URL",
  "NEXT_PUBLIC_YOUTUBE_URL",
  "PRIVATE_MESSAGING_ENABLED",
  "CHROME_PATH",
  "BCN_SOURCE_PREVIEW_ENABLE_LOCAL_CHROME",
  "BCN_SOURCE_PREVIEW_SCREENSHOT_URL_TEMPLATE"
];

// Migration and seed authority never enters either customer-facing runtime.
const TOOLING_ONLY_KEYS = ["POSTGRES_PASSWORD", "ADMIN_PASSWORD", "SEED_MODE"];

const REQUIRED_SHARED_KEYS = [
  "DATABASE_URL",
  "AUTH_SECRET",
  "NEXTAUTH_SECRET",
  "STRIPE_SECRET_KEY",
  "STRIPE_CIRCLE_CARD_PRO_PRODUCT_ID",
  "STRIPE_CIRCLE_CARD_PRO_MONTHLY_PRICE_ID",
  "CIRCLE_CARD_BILLING_PORTAL_CONFIGURATION_ID",
  "CIRCLE_CARD_BILLING_ENABLED",
  "CIRCLE_CARD_BILLING_ACCESS_MODE",
  "CLOUDINARY_CLOUD_NAME",
  "CLOUDINARY_API_KEY",
  "CLOUDINARY_API_SECRET"
];

const REQUIRED_BCN_KEYS = [
  "STRIPE_WEBHOOK_SECRET",
  "RESEND_API_KEY",
  "RESEND_FROM_EMAIL",
  "RESEND_REPLY_TO_EMAIL",
  "PUBLIC_CONTACT_EMAIL",
  "RESEND_WEBHOOK_SECRET",
  "INBOUND_EMAIL_FORWARD_TO",
  "CRON_SECRET",
  "LIVEKIT_URL",
  "TURN_DOMAIN",
  "TURN_TLS_ENABLED",
  "TURN_TLS_PORT",
  "TURN_TLS_CERT_FILE",
  "TURN_TLS_KEY_FILE"
];

const REQUIRED_CIRCLE_KEYS = [...CIRCLE_CARD_ONLY_KEYS];
const BCN_ALLOWED_KEYS = [...new Set([...SHARED_KEYS, ...BCN_ONLY_KEYS, ...CIRCLE_LIFECYCLE_KEYS])];
const CIRCLE_ALLOWED_KEYS = [...new Set([...SHARED_KEYS, ...CIRCLE_CARD_ONLY_KEYS])];

const RUNTIME_VALUES = {
  bcn: {
    NODE_ENV: "production",
    APP_BRAND: "bcn",
    APP_URL: "https://thebusinesscircle.net",
    AUTH_URL: "https://thebusinesscircle.net",
    NEXTAUTH_URL: "https://thebusinesscircle.net",
    NEXT_RUNTIME_DIST_DIR: ".runtime/bcn",
    PORT: "3000",
    HOSTNAME: "127.0.0.1"
  },
  "circle-card": {
    NODE_ENV: "production",
    APP_BRAND: "circle-card",
    APP_URL: "https://circlecard.co.uk",
    AUTH_URL: "https://circlecard.co.uk",
    NEXTAUTH_URL: "https://circlecard.co.uk",
    NEXT_RUNTIME_DIST_DIR: ".runtime/circle-card",
    PORT: "3200",
    HOSTNAME: "127.0.0.1",
    BCN_COMMUNITY_AUTOMATION_ENABLED: "false"
  }
};

module.exports = {
  APPROVED_SHA: FORWARD_APPLICATION_SHA,
  FORWARD_APPLICATION_SHA,
  HISTORICAL_PRODUCTION_SHA,
  ROLLBACK_APPLICATION_SHA,
  BCN_ALLOWED_KEYS,
  BCN_ONLY_KEYS,
  BUILD_ENV_KEYS,
  CIRCLE_ALLOWED_KEYS,
  CIRCLE_LIFECYCLE_KEYS,
  CIRCLE_CARD_ONLY_KEYS,
  DELIBERATELY_UNSUPPORTED_KEYS,
  REQUIRED_BCN_KEYS,
  REQUIRED_CIRCLE_KEYS,
  REQUIRED_SHARED_KEYS,
  RUNTIME_VALUES,
  SHARED_KEYS,
  TOOLING_ONLY_KEYS
};
