ALTER TYPE "ModerationEntityType" ADD VALUE IF NOT EXISTS 'COMMUNITY_POST';
ALTER TYPE "ModerationEntityType" ADD VALUE IF NOT EXISTS 'COMMUNITY_COMMENT';
ALTER TYPE "ModerationEntityType" ADD VALUE IF NOT EXISTS 'COMMUNITY_BULK';

ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'COMMUNITY_DELETE_ALL_COMMENTS';
ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'COMMUNITY_DELETE_ALL_POSTS_AND_COMMENTS';
ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'COMMUNITY_DELETE_POST';
ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'COMMUNITY_DELETE_COMMENT';
