ALTER TYPE "CircleCardEventType" ADD VALUE 'DISCOVER_SEARCH';
ALTER TYPE "CircleCardEventType" ADD VALUE 'DISCOVER_CARD_VIEWED';
ALTER TYPE "CircleCardEventType" ADD VALUE 'DISCOVER_CARD_SAVED';
ALTER TYPE "CircleCardEventType" ADD VALUE 'DISCOVER_CONNECTION_REQUEST_SENT';
