ALTER TYPE "CircleCardEventType" ADD VALUE 'CARD_LINK_RESOLVED';
ALTER TYPE "CircleCardEventType" ADD VALUE 'CARD_LINK_RESOLVE_FAILED';
ALTER TYPE "CircleCardEventType" ADD VALUE 'CONNECT_HUB_SHARE';
ALTER TYPE "CircleCardEventType" ADD VALUE 'CONNECT_HUB_COPY_LINK';
